Задание 1
Rafael-Minnigaliev/taxi pull request #1
Opened 2022-05-30 08:59 UTC by Rafael-Minnigaliev

2022-05-30 09:16 UTC, NizamovArturV requested changes

2022-05-30 09:16 UTC, NizamovArturV commented on local/php_interface/init.php
> +CModule::IncludeModule("sprint.options");
Используем d7 (почитай что это), подключаем через Bitrix\Main\Loader

2022-05-30 09:16 UTC, NizamovArturV commented on local/templates/taxi/components/bitrix/menu/menu/.description.php
> +<?
Зачем нужен этот файл? Как ты его используешь?

2022-05-30 09:16 UTC, NizamovArturV commented on local/templates/taxi/components/bitrix/menu/menu/.description.php
> +	"NAME" => GetMessage("MENU_DOT_DEFAULT_NAME"),
Если используешь, то получение языковых переменных d7 (Bitrix\Main\Localization\Loc)

2022-05-30 09:16 UTC, NizamovArturV commented on local/templates/taxi/components/bitrix/menu/menu/lang/en/.description.php
> +$MESS ['MENU_DOT_DEFAULT_NAME'] = "Default vertical menu";
Используем одинарные кавычки

2022-05-30 09:16 UTC, NizamovArturV commented on local/templates/taxi/components/bitrix/menu/menu/template.php
> +<?php if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
Оформление не по PSR

2022-05-30 09:16 UTC, NizamovArturV commented on local/templates/taxi/components/bitrix/menu/menu/template.php
> +                <li class="menu-item"><a href="<?=$arItem["LINK"]?>"><?=$arItem["TEXT"]?></a></li>
Ключи массива - одинарные кавычки

2022-05-30 09:16 UTC, NizamovArturV commented on local/templates/taxi/components/bitrix/menu/menu/template.php
> +        <a class="roundBtn" href="tel:+79991234569"><?=sprint_options_get('PHONE')?></a>
Телефон в ссылке захардкожен

2022-05-30 09:16 UTC, NizamovArturV commented on local/templates/taxi/description.php
> +	'NAME' => 'Шаблон сайта такси',
В lang файлы

2022-05-30 09:16 UTC, NizamovArturV commented on local/templates/taxi/header.php
> +<?php
Оформление не по PSR

2022-05-30 09:16 UTC, NizamovArturV commented on local/templates/taxi/header.php
> +    <!--<?php //$APPLICATION->SetAdditionalCSS(SITE_TEMPLATE_PATH.'/css/aos.css');?>-->
Зачем?

2022-05-30 09:16 UTC, NizamovArturV commented on local/templates/taxi/header.php
> +    <?php $APPLICATION->SetAdditionalCSS(SITE_TEMPLATE_PATH.'/css/style.css');?>
Подключаем стили через d7 методы

2022-05-30 09:16 UTC, NizamovArturV commented on local/templates/taxi/header.php
> +				"MENU_CACHE_TYPE" => "N",
Почему N?

2022-05-30 09:16 UTC, NizamovArturV commented on local/templates/taxi/header.php
> +				"USE_EXT" => "N"
Почему N?

2022-05-30 09:16 UTC, NizamovArturV commented on robots.txt
> +User-agent: *
Почему файл в гитгнор, но сам файл здесь есть?

2022-05-30 09:20 UTC, NizamovArturV commented on local/templates/taxi/footer.php
> +<?php $APPLICATION->AddHeadScript('https://unpkg.com/swiper@7/swiper-bundle.min.js')?>
Скрипты подключаем в файле header.php, если нужно перенести в конце - в главном модуле есть настройка

2022-05-30 10:09 UTC, Rafael-Minnigaliev commented on local/templates/taxi/components/bitrix/menu/menu/.description.php
> +<?
Описание для работы с компонентом. Это описание применяется для работы с компонентом а также при работе в режиме редактирования сайта. На работу самого компонента не влияет. Я его никак не использовал думаю в данном случае его можно не переопределять соответственно удалить.

2022-05-30 10:26 UTC, Rafael-Minnigaliev commented on local/templates/taxi/header.php
> +    <!--<?php //$APPLICATION->SetAdditionalCSS(SITE_TEMPLATE_PATH.'/css/aos.css');?>-->
Видимо закомменчена ссылка старой версии стилей для анимаций

2022-05-30 10:48 UTC, Rafael-Minnigaliev commented on local/templates/taxi/header.php
> +				"MENU_CACHE_TYPE" => "N",
По моему это NOT

2022-05-30 10:48 UTC, Rafael-Minnigaliev commented on local/templates/taxi/header.php
> +				"USE_EXT" => "N"
По моему это NOT

2022-05-30 11:03 UTC, NizamovArturV commented on local/templates/taxi/header.php
> +    <!--<?php //$APPLICATION->SetAdditionalCSS(SITE_TEMPLATE_PATH.'/css/aos.css');?>-->
Значит можно удалять

2022-05-30 11:04 UTC, NizamovArturV commented on local/templates/taxi/header.php
> +				"MENU_CACHE_TYPE" => "N",
Вопрос в другом, почему в этом значении, а не в другом?

2022-05-30 11:04 UTC, NizamovArturV commented on local/templates/taxi/header.php
> +				"USE_EXT" => "N"
Вопрос в другом, почему в этом значении, а не в другом?

2022-05-30 11:17 UTC, Rafael-Minnigaliev commented on robots.txt
> +User-agent: *
видимо гит в игнор добавил его после того как проиндексировал, нужно их удалить из репы и сделать новый коммит

2022-05-30 11:38 UTC, NizamovArturV requested changes

2022-05-30 11:38 UTC, NizamovArturV commented on local/php_interface/init.php
> +CModule::IncludeModule("sprint.options");
Не исправлено

2022-05-30 11:38 UTC, NizamovArturV commented on local/templates/taxi/components/bitrix/menu/menu/lang/en/.description.php
> +$MESS ['MENU_DOT_DEFAULT_NAME'] = "Default vertical menu";
Не исправлено

2022-05-30 11:38 UTC, NizamovArturV commented on local/templates/taxi/components/bitrix/menu/menu/template.php
> +<?php if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
Не исправлено

2022-05-30 12:14 UTC, Rafael-Minnigaliev commented on local/templates/taxi/header.php
> +				"MENU_CACHE_TYPE" => "N",
"MENU_CACHE_TYPE" => "N" не кешировать

2022-05-30 12:16 UTC, Rafael-Minnigaliev commented on local/templates/taxi/header.php
> +				"USE_EXT" => "N"
нельзя подключить файлы с именами:  .тип_меню.menu_ext.php.

2022-05-30 12:18 UTC, Rafael-Minnigaliev commented on local/templates/taxi/header.php
> +				"USE_EXT" => "N"
используются при реализации динамического меню

2022-05-30 12:31 UTC, NizamovArturV requested changes

2022-05-30 12:31 UTC, NizamovArturV commented on local/templates/taxi/components/bitrix/menu/menu/template.php
> +        <a class="roundBtn" href="tel:+79991234569"><?= sprint_options_get('PHONE') ?></a>
Телефон захардкожен

2022-05-30 12:31 UTC, NizamovArturV commented on local/templates/taxi/components/bitrix/menu/menu/template.php
> +			<?php foreach ($arResult as $arItem): ?>
Оформление не по PSR

2022-05-30 12:31 UTC, NizamovArturV commented on local/templates/taxi/footer.php
> +<?php $APPLICATION->AddHeadScript('https://unpkg.com/swiper@7/swiper-bundle.min.js')?>
Не исправлено

2022-05-30 12:31 UTC, NizamovArturV commented on local/templates/taxi/header.php
> +				"MENU_CACHE_TYPE" => "N",
Почему не кэшируется?

2022-05-30 12:31 UTC, NizamovArturV commented on local/templates/taxi/header.php
> +				"USE_EXT" => "N"
Хорошо

2022-05-30 12:31 UTC, NizamovArturV commented on local/templates/taxi/description.php
> +	'NAME' => 'Шаблон сайта такси',
Не исправлено

2022-05-30 12:42 UTC, Rafael-Minnigaliev commented on local/templates/taxi/header.php
> +				"MENU_CACHE_TYPE" => "N",
N - Не кешировать: кеширования нет в любом случае.

2022-05-30 12:50 UTC, NizamovArturV requested changes

2022-05-30 12:50 UTC, NizamovArturV commented on local/templates/taxi/components/bitrix/menu/menu/template.php
> +        <a class="roundBtn" href="#"><?= sprint_options_get('PHONE') ?></a>
У тебя сейчас ссылка вообще осталась пустая

2022-05-30 16:40 UTC, Rafael-Minnigaliev commented on local/templates/taxi/components/bitrix/menu/menu/.description.php
> +	"NAME" => GetMessage("MENU_DOT_DEFAULT_NAME"),
не использовал

2022-05-31 04:03 UTC, Rafael-Minnigaliev commented on local/templates/taxi/header.php
> +				"MENU_CACHE_TYPE" => "N",
При работе с меню создается большой кеш что загружает систему

2022-05-31 06:31 UTC, NizamovArturV commented on local/templates/taxi/header.php
> +				"MENU_CACHE_TYPE" => "N",
Постоянные запросы загружают систему, кэш систему не загружает. Меню кэшируем

2022-06-01 07:17 UTC, merged